### ISSUE TITLE
Saving glyph "undefined" to "fontelloFont/undefined.svg"

### ISSUE THREAD

**Issue by Jab2870** [nfroidure/svgfont2svgicons#10]
This is the output I'm getting

```
Saving glyph "undefined" to "fontelloFont/undefined.svg"
/usr/lib/node_modules/svgfont2svgicons/bin/svgfont2svgicons.js:21
      glyph.stream.pipe(Fs.createWriteStream(glyphPath));
                   ^

TypeError: Cannot read property 'pipe' of undefined
    at SVGFont2SVGIcons.<anonymous> (/usr/lib/node_modules/svgfont2svgicons/bin/svgfont2svgicons.js:21:20)
    at emitNone (events.js:105:13)
    at SVGFont2SVGIcons.emit (events.js:207:7)
    at emitReadable_ (/usr/lib/node_modules/svgfont2svgicons/node_modules/plexer/node_modules/readable-stream/lib/_stream_readable.js:456:10)
    at emitReadable (/usr/lib/node_modules/svgfont2svgicons/node_modules/plexer/node_modules/readable-stream/lib/_stream_readable.js:450:7)
    at readableAddChunk (/usr/lib/node_modules/svgfont2svgicons/node_modules/plexer/node_modules/readable-stream/lib/_stream_readable.js:206:11)
    at SVGFont2SVGIcons.Readable.push (/usr/lib/node_modules/svgfont2svgicons/node_modules/plexer/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at SVGFont2SVGIcons.Duplexer._pushAll (/usr/lib/node_modules/svgfont2svgicons/node_modules/plexer/src/index.js:123:31)
    at PassThrough.<anonymous> (/usr/lib/node_modules/svgfont2svgicons/node_modules/plexer/src/index.js:102:13)
    at emitNone (events.js:105:13)
```

**Comment by chrisb34** [comment]
Is there a solution to this?

**Comment by javascriptlove** [comment]
Apparently the version in npm differs from master, we had to point to specific commit:

```
    "svgfont2svgicons": "https://github.com/nfroidure/svgfont2svgicons#249afa1953ec230a8b1e16073b9a9b986ca03e65",
```

**Comment by cdauth** [comment]
Fix:
```diff
diff --git a/bin/svgfont2svgicons.js b/bin/svgfont2svgicons.js
index 2ea7627..ad1b4e8 100755
--- a/bin/svgfont2svgicons.js
+++ b/bin/svgfont2svgicons.js
@@ -31,11 +31,7 @@ fontStream.pipe(iconProvider);
 iconProvider.on('readable', function() {
   var glyph;
   while((glyph = iconProvider.read()) !== null) {
-    var glyphName = glyph.metadata.name,
-      readableHex = glyph.metadata.unicode.map(function(str) {
-        return '\\u' + str.charCodeAt(0).toString(16).toUpperCase();
-      }).join('');
-
+    var glyphName = glyph.metadata.name;
     var glyphPath = path.join(destPath, glyphName + '.svg');
     console.log('Saving glyph "' + glyphName + '" to "' + glyphPath + '"');
     glyph.pipe(Fs.createWriteStream(glyphPath));
```
